CREATE DATABASE michaelangelo;


CREATE TABLE SUPPLIER(
	SUPPLIER_ID INT PRIMARY KEY AUTO_INCREMENT,
	SUPPLIER_NAME char(20),
	SUPPLIER_ADDRESS char(20),
	SUPPLIER_NUM INT,
	SUPPLIER_MATERIAL VARCHAR(20)
	);

CREATE TABLE MATERIAL(
	MATERIAL_ID INT PRIMARY KEY AUTO_INCREMENT,
	SUPPLIER_ID INT,
	MATERIAL_NAME char(20),
	MATERIAL_UNIT VARCHAR(10),
	MATERIAL_QTY INT,
	MATERIAL_PRICE INT
	);

CREATE TABLE MATERIAL_BOX(
	MATERIAL_BOXID INT PRIMARY KEY,
	MATERIAL_ID INT,
	BOX_NAME char(20)
	);

CREATE TABLE MATERIAL_ORDER(
	MATERIAL_ORDERID INT PRIMARY KEY,
	MATERIAL_ID INT,
	ORDER_DATE INT
	);

CREATE TABLE CUSTOMER_ORDER(
	CUSTOMER_ORDERID INT PRIMARY KEY,
	PRODUCT_ID INT,
	CUSTOMER_ID INT,
	ORDERQTY INT
	);

CREATE TABLE STORE(
	STOREID INT PRIMARY KEY,
	CUSTOMER_ORDERID INT,
	MATERIAL_ORDERID INT,
	EMPLOYEE_NAME char(30)
	);

CREATE TABLE CUSTOMER(
	CUSTOMER_ID INT PRIMARY KEY AUTO_INCREMENT,
	CUSTOMER_NAME char(30),
	PRIORITY_NUMBER INT
	);


CREATE TABLE PRODUCT(
	PRODUCT_ID INT PRIMARY KEY,
	PRODUCT_ORDERID INT,
	PRODUCT_QTY INT
	);

CREATE TABLE ORDER_INVOICE(
	ORDER_INVOICEID INT PRIMARY KEY,
	CUSTOMER_ORDERID INT,
	ORDER_INVOICE_AMOUNT INT
	);

CREATE TABLE PRODUCT_ORDER(
	PRODUCT_ORDERID INT PRIMARY KEY,
	MATERIAL_BOXID INT,
	PRODUCT_ORDER_DATE INT
	);

ALTER TABLE MATERIAL
	ADD CONSTRAINT FOREIGN KEY (SUPPLIER_ID) REFERENCES SUPPLIER(SUPPLIER_ID);

ALTER TABLE MATERIAL_BOX
	ADD CONSTRAINT FOREIGN KEY (MATERIAL_ID) REFERENCES MATERIAL(MATERIAL_ID);

ALTER TABLE MATERIAL_ORDER
	ADD CONSTRAINT FOREIGN KEY (MATERIAL_ID) REFERENCES MATERIAL(MATERIAL_ID);

ALTER TABLE CUSTOMER_ORDER
	ADD CONSTRAINT FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID),
	ADD CONSTRAINT FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID);

ALTER TABLE STORE
	ADD CONSTRAINT FOREIGN KEY (MATERIAL_ORDERID) REFERENCES MATERIAL_ORDER(MATERIAL_ORDERID),
	ADD CONSTRAINT FOREIGN KEY (CUSTOMER_ORDERID) REFERENCES CUSTOMER_ORDER(CUSTOMER_ORDERID);

ALTER TABLE PRODUCT
	ADD CONSTRAINT FOREIGN KEY (PRODUCT_ORDERID) REFERENCES PRODUCT_ORDER(PRODUCT_ORDERID);

ALTER TABLE ORDER_INVOICE
	ADD CONSTRAINT FOREIGN KEY (CUSTOMER_ORDERID) REFERENCES CUSTOMER_ORDER(CUSTOMER_ORDERID);

ALTER TABLE PRODUCT_ORDER
	ADD CONSTRAINT FOREIGN KEY (MATERIAL_BOXID) REFERENCES MATERIAL_BOX(MATERIAL_BOXID);
